### PR TITLE
Moved colourscheme to colors folder and improved README

### PR DESCRIPTION
**Pull request by J0sueTM**
Now we are able to install galaxian through vim package managers.

### CODE REVIEW

**Comment by evprkr** [comment]
Thanks for the help!

**Comment by evprkr** [comment]
Thanks for the help!

**Review by leftbones — APPROVED** [review]
Looks good!

**Review by leftbones — APPROVED** [review]
My internet is being ridiculously slow. Not sure I got everything right, but it all should be fine now.

**Review by leftbones — APPROVED** [review]

**Pull request merged**
